#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("MaskedEditText.Resource", IsApplication=true)]

namespace MaskedEditText
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int char_representation = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int mask = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int mask_fill = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050004
			public const int changingText = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int charRepButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int cpfEdit = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int dateEdit = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int maskButton = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int phoneEdit = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int phoneEditWithHint = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MaskedEditText = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MaskedEditText_char_representation = 1;
			
			// aapt resource value: 0
			public const int MaskedEditText_mask = 0;
			
			// aapt resource value: 2
			public const int MaskedEditText_mask_fill = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
